[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
merkle_airdrop = "9RenkeTQuM8nfvMkNLUA3fqWhn8ueHNkF3BfW3CyLf6S"
token_contract = "JCbkaacRtqB84vD3wsvgecG5VGQPUSL6ziA4GXkjRnEJ"

[programs.localnet]
token_contract = "JCbkaacRtqB84vD3wsvgecG5VGQPUSL6ziA4GXkjRnEJ"
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
