[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
merkle_airdrop = "9RenkeTQuM8nfvMkNLUA3fqWhn8ueHNkF3BfW3CyLf6S"

[programs.localnet]
my_program = "JCbkaacRtqB84vD3wsvgecG5VGQPUSL6ziA4GXkjRnEJ" # your program ID
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" # official SPL Token


[registry]
url = "https://api.apr.dev"


[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
